# Generated by Django 5.2.3 on 2025-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
