# Generated by Django 5.2.3 on 2025-07-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_file',
        ),
    ]
