# Generated by Django 5.2.3 on 2025-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobapplication_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
