# Generated by Django 5.2.3 on 2025-07-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
