services:
  - type: web
    name: jobtracker-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn jobtracker.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-app.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: jobtracker-db
          property: connectionString

databases:
  - name: jobtracker-db
